// The artist pages' data (`npm run artists`, and before every `npm run dev` / `npm run build`): reads each character folder of the
// repo (characters/<slug>/refs.json + bible.md + social.md; a folder without refs.json, like the unnamed Borat-type's, is left out
// until it has one) into src/generated/artists.json, and copies the local images the page shows (assets/characters/<slug>/spec.png,
// turnaround.jpg, avatar.png) to public/artists/<slug>/ (gitignored: media never goes into git, the build makes the copies).
//
// The JSON is committed, so the app builds and its tests run even where the repo's other folders are not there (a build that only
// sees terminal/): then this script keeps the committed file, makes no image copies, and the page falls back to the Higgsfield CDN
// image and its own empty states. Nothing here is fetched from the network.
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArtist } from './bible.mjs';

const TERMINAL = join(dirname(fileURLToPath(import.meta.url)), '..');
const REPO = join(TERMINAL, '..');
const CHARACTERS = join(REPO, 'characters');
const ASSETS = join(REPO, 'assets', 'characters');
const OUT_JSON = join(TERMINAL, 'src', 'generated', 'artists.json');
const OUT_IMAGES = join(TERMINAL, 'public', 'artists');
const IMAGES = { spec: 'spec.png', turnaround: 'turnaround.jpg', avatar: 'avatar.png' };

const read = (path) => (existsSync(path) ? readFileSync(path, 'utf8') : '');

function main() {
  if (!existsSync(CHARACTERS)) {
    console.log(`artists: ${CHARACTERS} is not here; keeping the committed src/generated/artists.json, no image copies`);
    return;
  }
  rmSync(OUT_IMAGES, { recursive: true, force: true });
  const artists = [];
  for (const slug of readdirSync(CHARACTERS).sort()) {
    const dir = join(CHARACTERS, slug);
    if (!existsSync(join(dir, 'refs.json'))) continue;
    let refs;
    try {
      refs = JSON.parse(readFileSync(join(dir, 'refs.json'), 'utf8'));
    } catch (e) {
      throw new Error(`characters/${slug}/refs.json is not valid JSON: ${e.message}`);
    }
    if (refs.slug !== slug) throw new Error(`characters/${slug}/refs.json says slug ${JSON.stringify(refs.slug)}`);
    const files = {};
    for (const [key, file] of Object.entries(IMAGES)) {
      const src = join(ASSETS, slug, file);
      if (!existsSync(src)) continue;
      mkdirSync(join(OUT_IMAGES, slug), { recursive: true });
      copyFileSync(src, join(OUT_IMAGES, slug, file));
      files[key] = true;
    }
    artists.push(parseArtist(refs, read(join(dir, 'bible.md')), read(join(dir, 'social.md')), files));
  }
  mkdirSync(dirname(OUT_JSON), { recursive: true });
  const json = `${JSON.stringify({ _doc: 'Generated by scripts/build-artists.mjs from characters/*/ (refs.json, bible.md, social.md): do not edit by hand.', artists }, null, 1)}\n`;
  if (read(OUT_JSON) !== json) writeFileSync(OUT_JSON, json);
  console.log(`artists: ${artists.map((a) => a.slug).join(', ')} -> src/generated/artists.json, images in public/artists/`);
}

main();
